# Generated by Django 3.2.9 on 2021-11-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NotesPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('position', models.PositiveIntegerField()),
                ('dashboard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spumAPP.dashboard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PluginType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('type_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('pwd_hash', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TasksPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('position', models.PositiveIntegerField()),
                ('dashboard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spumAPP.dashboard')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spumAPP.plugintype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TasksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('due_date', models.DateTimeField()),
                ('priority', models.IntegerField()),
                ('plugin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spumAPP.notesplugin')),
            ],
        ),
        migrations.AddField(
            model_name='notesplugin',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spumAPP.plugintype'),
        ),
        migrations.CreateModel(
            name='NotesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('plugin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spumAPP.notesplugin')),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spumAPP.user'),
        ),
    ]
