# Generated by Django 3.2.9 on 2022-01-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spumAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='habits_plugin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='spumAPP.habitsplugin'),
        ),
    ]
