# Generated by Django 3.2.9 on 2021-11-08 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spumAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksdata',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
