# Generated by Django 3.2.9 on 2021-11-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spumAPP', '0003_auto_20211108_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksdata',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
